version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: trocacerta-db
    environment:
      POSTGRES_DB: trocacerta_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - trocacerta-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trocacerta-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: trocacerta_dev
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - trocacerta-network
    command: npm run dev

  # Frontend (nginx serving static files)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trocacerta-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - trocacerta-network

volumes:
  postgres_data:

networks:
  trocacerta-network:
    driver: bridge
